# Generated by Django 3.2.4 on 2021-06-28 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cryptos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('closed_on', models.DateTimeField(blank=True, null=True)),
                ('margin', models.PositiveIntegerField()),
                ('entry_price', models.PositiveIntegerField()),
                ('exit_price', models.PositiveIntegerField()),
                ('leverage', models.PositiveIntegerField()),
                ('take_profit', models.IntegerField(blank=True, null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptos.pair')),
            ],
        ),
    ]
